version: 3

tasks:
  build:
    cmds:
      - ./gradlew build

  test:
    cmds:
      - java -jar ./build/libs/core-service-0.0.1-SNAPSHOT.jar

  deploy:
    cmds:
      - sudo systemctl start core.service
      - sudo systemctl status core.service
  
  status:
    cmds:
      - sudo systemctl status core.service
  stop:
    cmds:
      - sudo systemctl stop core.service
  
